new css ques
CodingNinjasCodes/InterQues pull request #125
Opened 2020-02-17 07:21 UTC by MounikaReddy15

2020-02-17 07:24 UTC, shivamyth requested changes

2020-02-17 07:24 UTC, shivamyth commented on css/answers/MounikaReddy15-q2.html
> +        <meta name="description" content="What are escape Sequences?">
Wrong content in meta tag.

2020-02-17 07:55 UTC, shivamyth requested changes

2020-02-17 07:55 UTC, shivamyth commented on css/answers/MounikaReddy15-q2.html
> +                    Tweening is the process in which we create intermediate frames between two images to get the appearance of the first image which develops into the second image.
Explain types of tweening and also write an example.

2020-02-19 07:33 UTC, dakshkhetan commented
@MounikaReddy15 Please make the requested changes as this PR will be closed in 24 hours if no changes are made.

2020-02-19 10:37 UTC, closed without merging