add question to the html
CodingNinjasCodes/InterQues pull request #130
Opened 2020-02-17 07:25 UTC by alpsz

2020-02-17 07:34 UTC, shivamyth requested changes

2020-02-17 07:34 UTC, shivamyth commented on html/answers/alps-q4.html
> +        <meta name="description" content="What is semantic HTML?">
You have added many unnecessary things. Correct it and resend the PR.

2020-02-19 07:28 UTC, dakshkhetan requested changes
@alpsz Please make the requested changes as this PR will be closed in 24 hours if no changes are made.

2020-02-19 07:28 UTC, dakshkhetan commented on html/answers/alps-q4.html
> +                Similar Questions
@alpsz "Similar Questions" is written two times in this file i.e. some lines of code have been duplicated/repeated.
Please make changes to your answer file ASAP.

2020-02-20 19:27 UTC, dakshkhetan commented
PR closed due to no response.

2020-02-20 19:27 UTC, closed without merging