Newq js interview
CodingNinjasCodes/InterQues pull request #142
Opened 2020-02-17 08:56 UTC by 23ashutosh3

add js quistion

2020-02-17 08:59 UTC, shivamyth requested changes

2020-02-17 08:59 UTC, shivamyth commented on javascript/answers/23ashutosh3-q23.html
> +                    Timers are used to execute a piece of code at a set time or also to repeat the code in a given interval of time. This is done by using the functions setTimeout, setInterval and cl
Add an example.

2020-02-17 09:05 UTC, 23ashutosh3 commented
Okk

On Mon, 17 Feb 2020, 14:29 shivamyth, <notifications@github.com> wrote:

> *@shivamyth* requested changes on this pull request.
> ------------------------------
>
> In javascript/answers/23ashutosh3-q23.html
> <https://github.com/CodingNinjasCodes/InterQues/pull/142#discussion_r380053057>
> :
>
> > +            </p>
> +        </div>
> +
> +
> +        <div>
> +            <div>
> +                <h4>
> +                    <h4> Explain the working of timers in JavaScript? Also elucidate the drawbacks of using the timer, if any?</h4>
> +                </h4>
> +            </div>
> +            <br>
> +            <br>
> +            <div>
> +                <strong>Answer:</strong>
> +                <p>
> +                    Timers are used to execute a piece of code at a set time or also to repeat the code in a given interval of time. This is done by using the functions setTimeout, setInterval and clearInterval.
>
> Add an example.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodingNinjasCodes/InterQues/pull/142?email_source=notifications&email_token=AOMBVT5AXJJTTLOESG7XWZLRDJGXVA5CNFSM4KWNFUGKYY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCVXKKLI#pullrequestreview-359572781>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOMBVT3A4HJ63AN2GKZ77ZDRDJGXVANCNFSM4KWNFUGA>
> .
>

2020-02-19 07:23 UTC, dakshkhetan commented
@23ashutosh3 Please make the requested changes as this PR will be closed in 24 hours if no changes are made.

2020-02-19 13:30 UTC, 23ashutosh3 commented
I will do it today

On Wed, 19 Feb 2020, 12:53 Daksh Khetan, <notifications@github.com> wrote:

> @23ashutosh3 <https://github.com/23ashutosh3> Please make the requested
> changes as this PR will be closed in 24 hours if no changes are made.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodingNinjasCodes/InterQues/pull/142?email_source=notifications&email_token=AOMBVTYPCZTOP7LL2LHRINTRDTNAJA5CNFSM4KWNFUGKYY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMGUS3Y#issuecomment-588073327>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOMBVTY6HO63DM4VCJHHXULRDTNAJANCNFSM4KWNFUGA>
> .
>

2020-02-20 19:26 UTC, dakshkhetan commented
Closing this PR, you can raise another one after making the requested changes.

2020-02-20 19:26 UTC, closed without merging