heres my my question
CodingNinjasCodes/InterQues pull request #155
Opened 2020-02-18 05:36 UTC by garunanurag

please let me know what can i do to improve

2020-02-18 17:36 UTC, dakshkhetan requested changes
@garunanurag You haven’t followed the contribution rules. Go through them in the documentation and also, look at other's format on how to add write your question in the `<ol>` list.

2020-02-19 08:54 UTC, garunanurag commented
> @garunanurag You haven’t followed the contribution rules. Go through them in the documentation and also, look at other's format on how to add write your question in the `<ol>` list.

i  have to put question in ol list  and is  answer part in the right format?

2020-02-21 09:12 UTC, garunanurag commented
i have  made some changes

2020-02-22 16:45 UTC, deepak-singh343 requested changes

2020-02-22 16:45 UTC, deepak-singh343 commented on javascript/index.html
> +            <li> what is event loop in JavaScript</li>>
There is an unnecassry ">" at the end of the line please remove it

2020-02-24 09:28 UTC, dakshkhetan requested changes
@garunanurag Why have you made changes in the GauravDwivedi-q9 file?

2020-02-24 09:28 UTC, dakshkhetan commented on javascript/answers/Anurag-Pandey-q35.html
> +                    &gt; What is NaN? What is its type? How can you reliably test if a value is equal to NaN?
Change this to your question title.

2020-02-24 09:28 UTC, dakshkhetan commented on javascript/answers/Anurag-Pandey-q35.html
> +        <meta name="description" content="What is NaN? What is its type? How can you reliably test if a value is equal to NaN?">
Change content="" to your question title

2020-02-24 09:40 UTC, deepak-singh343 commented
you have sent me by mistake this is not my PR

On Mon, 24 Feb, 2020, 2:58 PM Daksh Khetan, <notifications@github.com>
wrote:

> *@dakshkhetan* requested changes on this pull request.
>
> Why have you made changes in the GauravDwivedi-q9 file?
> ------------------------------
>
> In javascript/answers/Anurag-Pandey-q35.html
> <https://github.com/CodingNinjasCodes/InterQues/pull/155#discussion_r383153256>
> :
>
> > +        <link rel="shortcut icon" type="image/png" href="../../assets/favicon.png"/>
> +
> +        <meta name="description" content="What is NaN? What is its type? How can you reliably test if a value is equal to NaN?">
> +</head>
> +<body>
> +<div>
> +            <img src="../../assets/CN_logo.png" height='72px' alt="Coding Ninjas Logo">
> +        </div>
> +
> +        <div>
> +            <p>
> +                <small>
> +
> +                    <a href="../../index.html">Home</a>
> +                    &gt; <a href="../index.html">JavaScript Questions</a>
> +                    &gt; What is NaN? What is its type? How can you reliably test if a value is equal to NaN?
>
> Change this to your question title.
> ------------------------------
>
> In javascript/answers/Anurag-Pandey-q35.html
> <https://github.com/CodingNinjasCodes/InterQues/pull/155#discussion_r383153412>
> :
>
> > +	<!-- Global site tag (gtag.js) - Google Analytics -->
> +        <script async src="https://www.googletagmanager.com/gtag/js?id=UA-157837769-1"></script>
> +        <script>
> +        window.dataLayer = window.dataLayer || [];
> +        function gtag(){dataLayer.push(arguments);}
> +        gtag('js', new Date());
> +        gtag('config', 'UA-157837769-1');
> +        </script>
> +
> +        <title>
> +            JavaScript | InterQues | Coding Ninjas
> +        </title>
> +
> +        <link rel="shortcut icon" type="image/png" href="../../assets/favicon.png"/>
> +
> +        <meta name="description" content="What is NaN? What is its type? How can you reliably test if a value is equal to NaN?">
>
> Change content="" to your question title
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/CodingNinjasCodes/InterQues/pull/155?email_source=notifications&email_token=AOJPIEH3MM3Q7MADCAGEBILREOHNDA5CNFSM4KW5PPS2YY3PNVWWK3TUL52HS4DFWFIHK3DMKJSXC5LFON2FEZLWNFSXPKTDN5WW2ZLOORPWSZGOCWTMOAY#pullrequestreview-363251459>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AOJPIEHVY7BV22YAQ2HOG3TREOHNDANCNFSM4KW5PPSQ>
> .
>

2020-02-25 11:14 UTC, dakshkhetan commented
Closing this PR due to no changes done.
You can raise another after making requested changes.

2020-02-25 11:14 UTC, closed without merging