Added js question 22
CodingNinjasCodes/InterQues pull request #158
Opened 2020-02-21 13:01 UTC by Anamika2716

2020-02-24 09:10 UTC, dakshkhetan approved these changes
Looks good!

2020-02-25 11:07 UTC, dakshkhetan approved these changes

2020-02-25 11:10 UTC, dakshkhetan requested changes
@Anamika2716 Everything looks good, but first, please take a fresh pull `git pull upstream development` and then push your changes in order to resolve the conflicts.

2020-02-28 07:01 UTC, shivamyth commented
Haven't got any update on this PR from last 3 days. Closing it for now

2020-02-28 07:01 UTC, closed without merging