Css Question added
CodingNinjasCodes/InterQues pull request #170
Opened 2020-02-24 07:22 UTC by Meghraj1998

2020-02-24 07:26 UTC, arpansac requested changes

2020-02-24 07:26 UTC, arpansac commented on html/answers/meghraj-q7.html
> +                    It allows you to design a flexible responsive layout structure without using any float or positioning property of CSS.
Please add more description. Examples

2020-02-25 11:03 UTC, dakshkhetan commented
@Meghraj1998 Any updates on this? This PR will be closed in 24 hours if no changes are made.

2020-02-28 07:02 UTC, shivamyth commented
No updates on the PR, closing it for now.

2020-02-28 07:02 UTC, closed without merging