addednewquestion
CodingNinjasCodes/InterQues pull request #176
Opened 2020-02-24 07:47 UTC by ASHWINGS-coder

2020-02-24 07:49 UTC, shivamyth commented on css/index.html
> +                <a href="/Users/admin/Desktop/InterQues/css/answers/Ashwings-coder-q5.html">
href is incorrect

2020-02-24 07:51 UTC, shivamyth requested changes
Take a fresh pull, Your PR has many unnecessary changes.

2020-02-25 11:01 UTC, dakshkhetan commented
@ASHWINGS-coder Any updates on this? This PR will be closed in 24 hours if no changes are made.

2020-02-28 07:04 UTC, shivamyth commented
No updates on the PR, closing it for now.

2020-02-28 07:04 UTC, closed without merging