added JS question
CodingNinjasCodes/InterQues pull request #180
Opened 2020-02-24 08:34 UTC by pratik-dutta

please review and merge

2020-02-24 08:48 UTC, shivamyth requested changes
Change the question, this question is already available there in the repo

2020-02-25 10:59 UTC, dakshkhetan requested changes

2020-02-25 10:59 UTC, dakshkhetan commented on javascript/answers/pratik-dutta-q4.html
> +                    <p>While the <code>event.stopPropagation()</code> method stops the propogation of an event or it stops the event from occurring in the bubbling or capturing phase.</p>
@pratik-dutta Hey, please elaborate on your answer with examples if possible. :)

2020-02-28 07:09 UTC, shivamyth commented
No updates on the PR, closing it for now.

2020-02-28 07:09 UTC, closed without merging