Added new js Question
CodingNinjasCodes/InterQues pull request #181
Opened 2020-02-24 09:12 UTC by imashu001

2020-02-24 09:51 UTC, shivamyth requested changes

2020-02-24 09:51 UTC, shivamyth commented on javascript/answers/imashu001-q35.html
> +                    The onload function is not run until all the information on the page is loaded. This leads to a substantial delay before any code is executed.
Explain with an example

2020-02-25 10:52 UTC, dakshkhetan commented
@imashu001 Any updates on this? This PR will be closed in 24 hours if no changes are done.

2020-02-25 15:02 UTC, imashu001 reviewed
I have added code  Examples please have a look again

2020-02-25 15:04 UTC, imashu001 commented on javascript/answers/imashu001-q35.html
> +                    The onload function is not run until all the information on the page is loaded. This leads to a substantial delay before any code is executed.
@dakshkhetan @shivamyth  I have added code Examples please have a look again

2020-02-28 07:14 UTC, shivamyth submitted a review, later dismissed

2020-02-28 07:15 UTC, shivamyth approved these changes

2020-02-28 07:15 UTC, merged