added new css question
CodingNinjasCodes/InterQues pull request #231
Opened 2020-04-07 23:22 UTC by vineet30222

I added the new question ...that if div is given then how can you fit the image within the div...
It is responsive also....means if size page change then it should automatically fit the image

***new-question-updated-css**
**critical**
**pictorial-explaination**

2020-04-08 09:33 UTC, dakshkhetan requested changes
You have added CSS question but also made changes in the HTML folder.
Remove your file from HTML folder.

2020-04-08 17:27 UTC, vineet30222 commented
I have removed the file from the HTML folder...now review the update

2020-04-08 17:58 UTC, dakshkhetan commented
Resolve other requested changes too (check my comments corresponding your `css/answers/vineet30222-q12.html` file).
i.e. changing/editing question title at certain places.

2020-04-08 18:13 UTC, vineet30222 commented
updated the title in the answer file

2020-04-09 06:57 UTC, dakshkhetan requested changes
Change/edit question title on line 88 of your `css/answers/vineet30222-q12.html` file.

2020-04-09 06:57 UTC, dakshkhetan commented on css/answers/vineet30222-q12.html
> +        <meta name="description" content="What are the limits of the text field size?">
Change this to YOUR question title.

2020-04-09 06:57 UTC, dakshkhetan commented on css/answers/vineet30222-q12.html
> +                    &gt; What are the limits of the text field size?
Change this to YOUR question title.

2020-04-09 06:57 UTC, dakshkhetan commented on html/answers/vineet30222-q12.html
> +<html>
Delete this file.

2020-04-09 06:57 UTC, dakshkhetan commented on html/index.html
> +
Remove the extra spaces you have added in this file i.e. undo the changes.

2020-04-09 07:28 UTC, vineet30222 commented on css/answers/vineet30222-q12.html
> +                    &gt; What are the limits of the text field size?
done!

2020-04-09 07:29 UTC, vineet30222 commented on html/index.html
> +
done!

2020-04-09 07:43 UTC, dakshkhetan approved these changes

2020-04-09 07:43 UTC, merged