Question Added in Javascript
CodingNinjasCodes/InterQues pull request #281
Opened 2020-05-09 11:25 UTC by himalay12345

New Question added with no answer in present.

2020-05-26 14:59 UTC, dakshkhetan requested changes
@himalay12345 Please complete this PR by adding the answer.

2020-05-27 05:44 UTC, himalay12345 reviewed
I made the require changes.

2020-05-27 12:26 UTC, dakshkhetan requested changes

2020-05-27 12:26 UTC, dakshkhetan commented on javascript/answers/kumar-sourav-q45.html
> +               JavaScript classes introduced in ECMAScript 2015 is extremely similar to classes in C++ and Java in terms of syntax. But, it actually just provides a clearer and simpler syntax for the
Insert a code snippet to demonstrate on JavaScript classes.

2020-05-29 07:59 UTC, dakshkhetan commented
@himalay12345  Any updates? This PR will be closed in 24 hours if no changes are made.

2020-06-02 12:03 UTC, dakshkhetan commented
Closing due to no response.

2020-06-02 12:03 UTC, closed without merging