in CSS added ques 11
CodingNinjasCodes/InterQues pull request #289
Opened 2020-06-27 07:23 UTC by rawnakchourasia

Hello.. I have added question 11 in CSS. 

This is my first activity on github. There might be some mishaps. Kindly have a look. Thanks.

2020-06-27 14:49 UTC, dakshkhetan requested changes

2020-06-27 14:49 UTC, dakshkhetan commented on css/answers/rawnak-q11.html
> +        <meta name="description" content="Explain the concept of Tweening?">
Edit `content=""` to your question title.

2020-06-27 14:50 UTC, dakshkhetan requested changes
Hey @rawnakchourasia, everything's good except for one little thing.
Please see the [requested change](https://github.com/CodingNinjasCodes/InterQues/pull/289#discussion_r446534043) above. :)

2020-06-28 04:26 UTC, rawnakchourasia reviewed
changed 

content="" to my question

2020-06-28 04:26 UTC, rawnakchourasia commented on css/answers/rawnak-q11.html
> +                <br>
This is where I wrote the answer to it.

2020-06-28 04:41 UTC, dakshkhetan approved these changes
Looks good!

2020-06-28 04:41 UTC, merged