Newq programming question1
CodingNinjasCodes/InterQues pull request #34
Opened 2020-02-08 16:17 UTC by Anamika2716

Added one programming question

2020-02-10 05:56 UTC, arpansac requested changes
Please resolve as per the comments

2020-02-10 05:56 UTC, arpansac commented on .idea/InterQues.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this file from the commit

2020-02-10 05:56 UTC, arpansac commented on .idea/encodings.xml
> +<?xml version="1.0" encoding="UTF-8"?>
Remove this file

2020-02-10 05:56 UTC, arpansac commented on programming-editorials/index.html
> +        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
We're not using any css/bootstrap in this project :)

2020-02-10 05:56 UTC, arpansac commented on programming-editorials/index.html
> +         For a given distinct integer sequence of size N, the task is to count the number of contiguous increasing subsequence and contiguous decreasing subsequence in this sequence.
Interesting, can you please put the answer in a separate file. Please refer to the question from javascript

2020-02-10 15:28 UTC, Anamika2716 commented on .idea/InterQues.iml
> +<?xml version="1.0" encoding="UTF-8"?>
Updated code as per comments

2020-02-13 10:33 UTC, shivamyth commented on README.md
> + Thank fedllow developers if they help you out in any way
Change it.

2020-02-13 10:34 UTC, shivamyth requested changes
Take a fresh pull and update the PR, there are many issues in it highlighted by @arpansac resolve them also.

2020-02-13 10:35 UTC, shivamyth commented
You haven't changed anything in the last 3 days to this PR, so I am closing it

2020-02-13 10:35 UTC, closed without merging