Newq developement
CodingNinjasCodes/InterQues pull request #42
Opened 2020-02-10 08:55 UTC by Piyush-zlatan

2020-02-10 10:21 UTC, arpansac requested changes
Everything seems fine, you just need to resolve a conflict because someone added a question already. New thing to learn!

2020-02-10 12:15 UTC, Piyush-zlatan commented
> Everything seems fine, you just need to resolve a conflict because someone added a question already. New thing to learn!

resolved..!! please check

2020-02-11 09:59 UTC, arpansac requested changes

2020-02-11 09:59 UTC, arpansac commented on javascript/answers/q4.html
> +        <meta name="description" content="What will be the output of the code below?">
Please change the content="" part to be the text of the question

2020-02-11 09:59 UTC, arpansac commented on javascript/answers/q4.html
> +                    &gt; What will be the output of the code below?
Change this to the question text

2020-02-12 08:44 UTC, arpansac approved these changes

2020-02-12 08:45 UTC, merged