Added jsQues
CodingNinjasCodes/InterQues pull request #68
Opened 2020-02-11 16:06 UTC by Gyankr

Java Script new question added.

2020-02-12 09:11 UTC, arpansac requested changes

2020-02-12 09:11 UTC, arpansac commented on javascript/answers/q6.html
> +                    When you setTimeout it becomes asynchronous and it has to wait on the stack to get everything got finished.
Please elaborate on the answer

2020-02-13 07:44 UTC, gyanSDE commented on javascript/answers/q6.html
> +                    When you setTimeout it becomes asynchronous and it has to wait on the stack to get everything got finished.
1: Answer elaborated 
2: git add .
3: git commit -m 'elaborate ans'
4: git push origin newq-jsQues
//Anything more  i need to do Sir?

2020-02-13 07:46 UTC, Gyankr commented
Done sir

2020-02-13 10:52 UTC, shivamyth requested changes

2020-02-13 10:52 UTC, shivamyth commented on javascript/answers/q6.html
> +                    When you setTimeout it becomes asynchronous and it has to wait on the stack to get everything got finished.
Change the name of  answer  HTML file as the format, check the merged questions for example

2020-02-13 11:18 UTC, Gyankr commented on javascript/answers/q6.html
> +                    When you setTimeout it becomes asynchronous and it has to wait on the stack to get everything got finished.
Changed html file name

2020-02-13 11:23 UTC, Gyankr commented on javascript/index.html
> +                <a href="./answers/Gyan-Kr-q6.html">
Done

2020-02-14 06:54 UTC, arpansac submitted a review, later dismissed
Looks good. Can you please update it with a little better answer!

2020-02-14 06:55 UTC, arpansac approved these changes

2020-02-14 06:55 UTC, merged