Newq jsquestion8
CodingNinjasCodes/InterQues pull request #80
Opened 2020-02-12 12:46 UTC by kunalkr789

PR comments resolution

2020-02-13 10:24 UTC, shivamyth approved these changes

2020-02-14 07:02 UTC, arpansac requested changes
Just one small change

2020-02-14 07:02 UTC, arpansac commented on javascript/answers/kunalkr789-q8.html
> +                    &gt; What are escape Sequences?
Change this to the question text!

2020-02-14 14:39 UTC, kunalkr789 commented on javascript/answers/kunalkr789-q8.html
> +                    &gt; What are escape Sequences?
change is done

2020-02-15 08:24 UTC, dakshkhetan approved these changes
Looks good!

2020-02-15 08:25 UTC, merged