added new question
CodingNinjasCodes/InterQues pull request #84
Opened 2020-02-13 08:58 UTC by rahulsin14

2020-02-13 10:11 UTC, shivamyth commented on javascript/index.html
> +                <a href="./answers/rahulsin14_q7.html">
It should be hyphen there not an underscore

2020-02-13 10:13 UTC, shivamyth commented on javascript/answers/rahulsin14_q7.html
> +                <div>JavaScript allows DOM elements to be nested inside each other. In such a case, if the handler of the child is clicked, the handler of parent will also work as if it were clicked
Also, give an example of each one.

2020-02-13 10:16 UTC, shivamyth requested changes
Do the changes as commented

2020-02-14 07:08 UTC, arpansac requested changes
Changes requested

2020-02-14 07:08 UTC, arpansac commented on javascript/answers/rahulsin14_q7.html
> +        <meta name="description" content="Define Event Bubbling">
Put question text in content=""

2020-02-15 08:29 UTC, dakshkhetan commented
Any updates on this? This PR will be closed by tomorrow if no changes are done.

2020-02-17 06:22 UTC, shivamyth commented
No updates in the PR, closing it.

2020-02-17 06:22 UTC, closed without merging